### ISSUE TITLE
Update to PlayCanvas v1.32.3

### ISSUE THREAD

**Issue by willeastcott** [cx20/gltf-test#130] opened 2020-07-29 08:47 UTC
Updating to an official release version for the engine v1.32.3 fixes the Texture Settings Test:

![image](https://user-images.githubusercontent.com/697563/88778453-71979500-d180-11ea-8316-eef8d30d6653.png)

**Comment by cx20** [comment] 2020-07-29 12:05
@willeastcott I tried changing PlayCavnas to `v1.32.3`, but the Texture Settings Test didn't pass.

[PlayCanvas v1.32.3 + TextureSettingsTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/35718a0dc4d12133fe80ef5895f66bfd824970ec/examples/playcanvas/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/88797113-c5849700-d1dd-11ea-98de-11f6ccb6a7da.png)

Probably the usage has changed, but I don't know how to modify the code because there are many differences between the code in playcanvas-viewer and my viewer. I'm not so familiar with PlayCanvas so I think it will take some time to investigate how to fix it.
I would appreciate it if you could give me a PR to display it properly.

**Comment by slimbuck** [comment] 2020-07-30 11:58
Hi @cx20, 

Turns out this test was passing for the glTF-Binary model but not the glTF!

We weren't handling textures correctly, but that should now be fixed in https://github.com/playcanvas/engine/pull/2327.

So yeah, hopefully the next engine release will finally pass all the base tests! :D 

Thanks!

**Comment by cx20** [comment] 2020-07-30 15:23
I confirmed that PlayCanvas `v1.33.0-dev` fixed the problem.
[PlayCanvas v1.33.0-dev + TextureSettingsTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/a4e97d365f81db640c6cd09058485771b323a728/examples/playcanvas/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/88940865-46698e80-d2c3-11ea-9109-4e92fd4bd1c8.png)

Currently, the [test results](https://github.com/cx20/gltf-test#feature-test-models) for this model are green.
![image](https://user-images.githubusercontent.com/1833979/88941168-aa8c5280-d2c3-11ea-9b77-929612f9d115.png)

**Closed by cx20** 2020-07-30 15:23 UTC

**Comment by willeastcott** [comment] 2020-07-30 16:39
Awesome! It took a long time, but we now pass all of the core tests (minus the extensions). Thanks so much for all your help to get us there @cx20! We mentioned this repo in our blog announcement:

https://twitter.com/playcanvas/status/1288866660657528838
